# Generated by Django 5.0.2 on 2024-02-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Unassigned', 'Unassigned')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_warning',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
